name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t portfolio-devqaops:latest .
